run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - gofmt         # Check whether code was gofmt-ed
    - goimports     # Check import statements are formatted
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible linter
    - gosec         # Security problems
    - gocritic      # Opinionated linter
    - nolintlint    # Reports ill-formed or insufficient nolint directives
  disable:
    - unused        # Too noisy for private fields that may be used in future
    - unconvert     # Style issue, not a bug
    - unparam       # Too noisy
    - prealloc      # Micro-optimization

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives
      - fieldalignment  # Micro-optimization, not worth the noise

  revive:
    rules:
      - name: exported
        disabled: false
      - name: unexported-return
        disabled: true

  gosec:
    excludes:
      - G104  # Errors unhandled (handled by errcheck)

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - commentFormatting
      - whyNoLint
      - unnamedResult
      - sloppyReassign
      - unlambda

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - gocritic
        - errcheck
        - govet
        - unparam
        - revive
        - gosimple

    # Allow unsafe in specific files
    - path: utils_nalloc\.go
      linters:
        - gosec
      text: "G103.*unsafe"

    # Integer conversion warnings - mostly false positives for length conversions
    - linters:
        - gosec
      text: "G115"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
